services:
  - type: web
    name: callify
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false
      - key: REDIS_URL
        value: redis://localhost:6379
